[settings]

# config files with these prefixes will be trusted by default
trusted_config_paths = [
    '~/dev',
]

[tools]
# Basic tools
bat = "latest"
zoxide = "latest"
fd = "latest"
fzf = "latest"
hwatch = "latest"
jq = "latest"
neovim = "latest"
rg = "latest"
tmux = "latest"
yq = "latest"

# Kubernetes
k9s = "latest"
kubectl = "latest"
kubeswitch = "latest"
stern = "latest"

# GitHub
act = "latest"
gh = "latest"

# Dotfiles
chezmoi = "latest"

# Password Managers
1password-cli = "latest"
bitwarden = "latest"

# AI tools
opencode = "latest"
claude = "latest"
